databases:
  - name: movie-review-app
    databaseName: moviedb
    user: moviedbuser
    plan: free

services:
  - type: web
    name: movie-review-app
    runtime: ruby
    plan: free
    buildCommand: "chmod +x ./bin/rails && chmod +x ./bin/render-build.sh && ./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-review-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false